### ISSUE TITLE
Error when using Spotify

### ISSUE THREAD

**Issue by NeuesTwix** [justdotJS/SimplePresence#22]
## Checklist
- [x] I am on the latest version

- [x] I am on the latest version of dependencies

- [x] I have followed the instructions in the [Wiki](https://github.com/justdotJS/SimplePresence/wiki)
- [x] I am on the latest version of Discord

## Type
Please select what type of issue this is. Please do not use Issues for Support, [ask on the Discord](https://discord.gg/MpnbrX7)!

[ ] Feature Request

[x] Bug Report

## Description
I can use the custom or YouTube mode without issues but if I wanna use Spotify I get this error:
`{ Error: connect ECONNREFUSED 127.0.0.1:4381
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4381 }`

## Specifications
Version is the version of EasyRPC, Platform is Windows/macOS/Linux, and Platform Version is the version of the platform (e.g. 10.13.1 for macOS, or 10 for Windows.).
  - [x] Version: Newest
  - [x] Platform: MacOS
  - [x] Platform Version:  10.14.3

**Comment by eramsorgr** [comment]
I can not replicate the issue, what's your Spotify version?
